# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8939577e21d0d522fb547a26fc2c3ce34e1af14bed3d47c9144890253ade53f11ec0689e88856991c906055378bdefde28ccfaa9ccabd438417887b46dd6744d

test:
  secret_key_base: a5df390d5633ab721fc2241392cbf606569fa051f6b895ab72cae8bfdafda5d39cd3b1043c70cdaa84c470790d0934f4ec9531c5b40141535e5b27a1b1dbd632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
